# Generated by Django 3.0.7 on 2021-10-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meeting_time', models.TextField()),
                ('meeting_date', models.TextField()),
                ('remarks', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='video_app.Post')),
            ],
        ),
    ]
