# Generated by Django 3.0.7 on 2021-10-30 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='')),
                ('title', models.TextField(default='title', max_length=50, verbose_name='title')),
                ('category', models.TextField(default='category', max_length=50, verbose_name='category')),
            ],
        ),
    ]
