# Generated by Django 3.0.7 on 2021-10-30 16:56

from django.db import migrations, models
import video_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to=video_app.models.user_directory_path),
        ),
    ]
